-- Assumptions table to persist manual and inferred shipment parameters
create table if not exists public.report_assumptions (
  id bigint generated by default as identity primary key,
  report_id uuid not null references public.reports(id) on delete cascade,
  key text not null,
  value text,
  unit text,
  source text,
  confidence text,
  rationale text,
  range_json jsonb,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create unique index if not exists report_assumptions_report_key_idx on public.report_assumptions (report_id, key);
create index if not exists report_assumptions_report_id_idx on public.report_assumptions (report_id);
